apiVersion: v1
kind: Service
metadata:
  name: queue
spec:
  ports:
    - name: http
      port: 8161
      nodePort: 30010
  selector:
    app: queue

  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  ports:
    - name: http
      port: 80
      nodePort: 30080
  selector:
    app: webapp
    release: "0-5"

  type: NodePort